### ISSUE TITLE
Install with Brew? 

### ISSUE THREAD

**Issue by gregwym** [freshshell/fresh#104]
Hi, 

I just wondering can this tool be installed through Mac Homebrew? 

Thanks, 
Greg

**Comment by quintrino** [comment]
Hi, just wondering if this was still a possibility?

**Comment by jasoncodes** [comment]
Our reasons for not officially supporting installation via Homebrew have not changed. We recommend you update fresh via fresh rather than using an external mechanism such as Homebrew. If you really want to install fresh via Homebrew, please feel free to create a HEAD-only formula in your own Homebrew tap using the above formula as a reference.
