### ISSUE TITLE
a really dumb question

### ISSUE THREAD

**Issue by jayceekay** [freshshell/fresh#157]
i feel like an idiot, but i can't figure out how to accomplish my goal. i have my dotfiles hosted in a github repo (jayceekay/dotfiles) and i simply want to start by just pulling those down and installing them on my local. i thought this would be a use case for this tool, am i wrong?

edit: alternatively if i have all of my dotfiles as is (eg. in my home dir), after installing fresh is there something like `fresh init` which will take my existing dotfiles, put them in their own directory/repository, generate the freshrc to recreate this configuration on another computer, and symlink them into my home directory?

**Comment by jasoncodes** [comment]
Hi there. fresh does not yet have an init function to take over an existing dotfiles repository. This is a good idea for a future enhancement but unfortunately there are so many ways for one to arrange their dotfiles repo and that would make automatic configuration tricky.

You don’t seem to have a public dotfiles repo so I can’t write a starting a `freshrc` file for you so instead let’s take a look at [my dotfiles](https://github.com/jasoncodes/dotfiles) as an example.

You’ll see I have a `config/` dir for any plain dotfiles and then I have [`fresh config/\* --file` in my `freshrc`](https://github.com/jasoncodes/dotfiles/blob/beecd302dddc7dd0eb6192348e149f32cdb4bd01/freshrc#L18) which tells fresh to install all files in that directory. This is the [config files](https://github.com/freshshell/fresh#config-files) feature in action.

I’d also recommend having some [bootstrap](https://github.com/jasoncodes/dotfiles/blob/beecd302dddc7dd0eb6192348e149f32cdb4bd01/freshrc#L3-L6) lines for setting up fresh and your shell config. The fresh bin line is highly recommended as it installs fresh itself and the “source-build” lines bootstrap fresh’s shell config file.

Once you have created `~/.dotfiles/freshrc` you can then symlink that to `~/.freshrc` and install/run fresh. fresh reads from `~/.freshrc` but we recommend you keep it in your dotfiles repo and symlink to it. In the future, once you have fresh configured in the dotfiles, you can install your dotfiles on a clean machine using a [one liner](https://github.com/jasoncodes/dotfiles/blob/master/README.markdown).

I can provide more specific assistance if you’d like to either share your dotfiles repo or otherwise advise how your dotfiles are structured.

**Comment by jayceekay** [comment]
great explanation, it makes sense now. thanks a ton for the utility!

**Comment by jasoncodes** [comment]
Glad I could help and thanks for contacting us. I’ve updated #151 which deals with changing some our of install script defaults to see if we can make this process more obvious. Cheers.

**Comment by psprint** [comment]
I must say that after reading the explanation I felt being introduced, but somewhat didn't manage to reach the "eureka!" moment of grasping what fresh is. Could I ask for a few more sentences aimed at just that – at covering what fresh actually is?
